export type Material = {
  slug: string;
  name: string;
  category: string;
  badge: string;
  image: string;
  intro: string;
  application: string;
  properties: string;
  presentations: string[];
  specs: { label: string; value: string }[];
  chemistry?: { label: string; value: string }[];
  gallery?: { src: string; alt: string; label?: string }[];
  uses: string[];
  featured?: boolean;
};

export const categories = [
  "Aceros grado maquinaria",
  "Aceros inoxidables",
  "Antidesgaste",
  "No ferrosos",
  "Plásticos de ingeniería",
  "Consumibles y corte",
  "Estructurales",
];

export const materials: Material[] = [
  {
    slug: "aisi-1018-1020",
    name: "AISI / SAE 1018 - 1020",
    category: "Aceros grado maquinaria",
    badge: "Bajo carbono",
    image: "/images/products/aceros-grado-maquinaria-wow.webp",
    intro: "Acero calibrado de bajo contenido de carbono para piezas de baja exigencia mecánica, fácil mecanizado y buena soldabilidad.",
    application: "Utilizado en maquinaria y piezas como ejes de baja potencia, tornillos, engranes, piñones y componentes que no estén sometidos a altos esfuerzos.",
    properties: "Baja dureza, buena maquinabilidad, soldabilidad favorable y comportamiento confiable para trabajos industriales de uso general.",
    presentations: ["Barras redondas", "Barras cuadradas", "Barras hexagonales", "Platinas calibradas", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/acero-barra-cuadrada-hexagonal-12l14.webp", alt: "Barras cuadradas y hexagonales de acero", label: "Presentación de barras calibradas" },
    ],
    specs: [
      { label: "Dureza", value: "110 - 156 HB" },
      { label: "Esfuerzo de fluencia mín.", value: "27 kg/mm²" },
      { label: "Esfuerzo de tracción", value: "40 - 45 kg/mm²" },
      { label: "Elongación mín.", value: "20%" },
    ],
    chemistry: [
      { label: "%C", value: "0,18 - 0,23" },
      { label: "%Mn", value: "0,30 - 0,60" },
      { label: "%Si", value: "0,15 - 0,35" },
      { label: "%P", value: "≤ 0,04" },
      { label: "%S", value: "≤ 0,05" },
    ],
    uses: ["Talleres de maquinado", "Piezas de baja potencia", "Tornillería", "Engranes y piñones", "Platinas y barras de trabajo"],
    featured: true,
  },
  {
    slug: "aisi-1045",
    name: "AISI / SAE 1045",
    category: "Aceros grado maquinaria",
    badge: "Media resistencia",
    image: "/images/client-products/acero-aisi-1045.webp",
    intro: "Acero grado ingeniería con nivel medio de resistencia, recomendado para elementos endurecidos y componentes de mayor exigencia.",
    application: "Usado en ejes, manivelas, chavetas, pernos, tuercas, cadenas, engranajes de baja velocidad, espárragos, acoplamientos, bielas, pasadores y cigüeñales.",
    properties: "Ofrece una combinación equilibrada de dureza, tenacidad y resistencia mecánica para piezas industriales de uso frecuente.",
    presentations: ["Barras redondas", "Cortes a medida", "Material completo o fraccionado"],
    gallery: [
      { src: "/images/client-products/acero-aisi-1045.webp", alt: "Barra AISI 1045", label: "Barra maciza AISI 1045" },
    ],
    specs: [
      { label: "Dureza", value: "170 - 229 HB" },
      { label: "Esfuerzo de fluencia mín.", value: "40 kg/mm²" },
      { label: "Esfuerzo de tracción mín.", value: "63 - 73 kg/mm²" },
      { label: "Elongación mín.", value: "15%" },
    ],
    chemistry: [
      { label: "%C", value: "0,43 - 0,50" },
      { label: "%Mn", value: "0,60 - 0,90" },
      { label: "%Si", value: "0,15 - 0,35" },
      { label: "%P", value: "≤ 0,04" },
      { label: "%S", value: "≤ 0,05" },
    ],
    uses: ["Ejes", "Pernos y tuercas", "Cadenas", "Bielas", "Piezas estampadas"],
    featured: true,
  },
  {
    slug: "aisi-4140",
    name: "AISI / SAE 4140",
    category: "Aceros grado maquinaria",
    badge: "Alta tenacidad",
    image: "/images/client-products/acero-aisi-4140.webp",
    intro: "Acero de baja aleación diseñado para piezas sometidas a esfuerzo, desgaste y fatiga.",
    application: "Se emplea en ejes, pasadores, cigüeñales, barras de torsión, engranajes, tuercas, pernos de gran esfuerzo, árboles de transmisión, émbolos, bielas y rotores.",
    properties: "Muy buena resistencia al desgaste, templabilidad, tenacidad y comportamiento superior frente a fatiga en componentes industriales.",
    presentations: ["Barras redondas", "Cortes de precisión", "Suministro para maquinado"],
    gallery: [
      { src: "/images/client-products/acero-aisi-4140.webp", alt: "Barra AISI 4140", label: "Barra maciza AISI 4140" },
    ],
    specs: [
      { label: "Dureza estado bonificado", value: "260 - 320 HB" },
      { label: "Esfuerzo de fluencia mín.", value: "60 - 75 kg/mm²" },
      { label: "Esfuerzo de tensión mín.", value: "88 - 100 kg/mm²" },
      { label: "Elongación mín.", value: "10 - 18%" },
    ],
    chemistry: [
      { label: "%C", value: "0,38 - 0,43" },
      { label: "%Mn", value: "0,75 - 1,00" },
      { label: "%Cr", value: "0,80 - 1,10" },
      { label: "%Mo", value: "0,15 - 0,25" },
    ],
    uses: ["Árboles de transmisión", "Barras de torsión", "Pernos de alto esfuerzo", "Rotores", "Engranajes"],
    featured: true,
  },
  {
    slug: "aisi-4340",
    name: "AISI / SAE 4340",
    category: "Aceros grado maquinaria",
    badge: "Exigencia mecánica",
    image: "/images/client-products/acero-aisi-4340.webp",
    intro: "Acero de baja aleación al cromo, níquel y molibdeno, ideal para componentes sometidos a grandes esfuerzos dinámicos.",
    application: "Recomendado para cigüeñales, ejes de levas, árboles de transmisión, barras de torsión, ejes, vástagos, poleas, barras de perforación, discos de freno, piñones, pernos y tuercas de alta exigencia.",
    properties: "Gran templabilidad, elevada tenacidad y alta resistencia a la fatiga para repuestos críticos y piezas de ingeniería.",
    presentations: ["Barras redondas", "Cortes según requerimiento", "Material para fabricación de repuestos"],
    gallery: [
      { src: "/images/client-products/acero-aisi-4340.webp", alt: "Barra AISI 4340", label: "Barra maciza AISI 4340" },
    ],
    specs: [
      { label: "Dureza estado bonificado", value: "260 - 320 HRc" },
      { label: "Esfuerzo de fluencia", value: "65 - 80 kg/mm²" },
      { label: "Esfuerzo de tensión", value: "90 - 105 kg/mm²" },
      { label: "Elongación mín.", value: "10 - 18%" },
    ],
    chemistry: [
      { label: "%C", value: "0,38 - 0,43" },
      { label: "%Cr", value: "0,70 - 1,65" },
      { label: "%Ni", value: "1,60 - 2,00" },
      { label: "%Mo", value: "0,20 - 0,30" },
    ],
    uses: ["Repuestos de alta exigencia", "Barras de perforación", "Cigüeñales", "Poleas", "Discos de freno"],
  },
  {
    slug: "barra-hueca-st52",
    name: "Barra hueca ST52",
    category: "Aceros grado maquinaria",
    badge: "Tubo mecánico",
    image: "/images/client-products/acero-barra-hueca.webp",
    intro: "También conocida como Barra Sandvik o tubo mecánico, se usa para piezas con centro hueco y resistencia confiable.",
    application: "Aplicable en ejes huecos, árboles de transmisión, bujes, anillos, camisas, botellas, masas, manguitos y cilindros.",
    properties: "Acero al carbono con alto contenido de manganeso. Permite ahorro de material cuando la pieza requiere cavidad central.",
    presentations: ["Barra hueca", "Tubo mecánico", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/acero-barra-hueca.webp", alt: "Barra hueca ST52", label: "Tubo mecánico / barra hueca" },
    ],
    specs: [
      { label: "Dureza", value: "125 HB" },
      { label: "Esfuerzo de fluencia mín.", value: "355 MPa" },
      { label: "Esfuerzo de tracción", value: "500 - 650 MPa" },
      { label: "Elongación mín.", value: "21%" },
    ],
    chemistry: [
      { label: "%C máx.", value: "0,22" },
      { label: "%P máx.", value: "0,040" },
      { label: "%S máx.", value: "0,035" },
    ],
    uses: ["Bujes", "Camisas", "Cilindros", "Anillos", "Ejes huecos"],
    featured: true,
  },
  {
    slug: "inox-304",
    name: "Acero inoxidable AISI 304",
    category: "Aceros inoxidables",
    badge: "Corrosión",
    image: "/images/client-products/inox-barra-304.webp",
    intro: "Acero inoxidable austenítico con buena resistencia a la corrosión, no templable y no magnético.",
    application: "Frecuente en industria alimenticia, marítima, química, farmacéutica, arquitectónica y estructural.",
    properties: "Aleado con cromo y níquel, bajo contenido de carbono, fácilmente trabajado en frío y soldable por distintos métodos excepto oxicorte.",
    presentations: ["Barras redondas", "Barras cuadradas", "Platinas", "Angulares", "Tubos redondos y cuadrados", "Láminas lisas y corrugadas"],
    gallery: [
      { src: "/images/client-products/inox-barra-304.webp", alt: "Barra inoxidable 304", label: "Barra inoxidable 304" },
      { src: "/images/client-products/inox-tubo-redondo.webp", alt: "Tubo inoxidable redondo", label: "Tubo inoxidable redondo" },
      { src: "/images/client-products/inox-tubo-cuadrado.webp", alt: "Tubo inoxidable cuadrado", label: "Tubo inoxidable cuadrado" },
      { src: "/images/client-products/inox-platina.webp", alt: "Platina inoxidable", label: "Platina inoxidable" },
      { src: "/images/client-products/inox-angular.webp", alt: "Angular inoxidable", label: "Angular inoxidable" },
      { src: "/images/client-products/inox-lamina-lisa.webp", alt: "Lámina inoxidable lisa", label: "Lámina inoxidable lisa" },
    ],
    specs: [
      { label: "Esfuerzo de fluencia mín.", value: "205 MPa" },
      { label: "Esfuerzo de tracción mín.", value: "515 MPa" },
      { label: "Elongación mín.", value: "40%" },
      { label: "Dureza Brinell", value: "160 - 190 HB" },
    ],
    chemistry: [
      { label: "%Cr", value: "18,00 - 20,00" },
      { label: "%Ni", value: "8,00 - 11,00" },
      { label: "%C", value: "0,08" },
      { label: "%Mn", value: "2,00" },
    ],
    uses: ["Industria alimenticia", "Ambientes marítimos", "Estructuras", "Equipos químicos", "Arquitectura"],
    featured: true,
  },
  {
    slug: "inox-316l",
    name: "Acero inoxidable AISI 316L",
    category: "Aceros inoxidables",
    badge: "Molibdeno",
    image: "/images/client-products/inox-barra-316.webp",
    intro: "Inoxidable austenítico cromo-níquel con molibdeno, recomendado cuando se requiere mayor resistencia a corrosión y picaduras.",
    application: "Utilizado en petróleo y gas, equipos para alimentos, industria farmacéutica, minería e implantes médicos.",
    properties: "El contenido de molibdeno mejora la resistencia a picaduras en soluciones con cloruros y eleva el desempeño a temperaturas altas.",
    presentations: ["Barras", "Platinas", "Láminas", "Tubos", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/inox-barra-316.webp", alt: "Barra inoxidable 316L", label: "Barra inoxidable 316L" },
      { src: "/images/client-products/inox-lamina-estriada.webp", alt: "Lámina inoxidable estriada", label: "Lámina inoxidable estriada" },
    ],
    specs: [
      { label: "Esfuerzo de fluencia mín.", value: "290 MPa" },
      { label: "Esfuerzo de tracción mín.", value: "580 MPa" },
      { label: "Elongación mín.", value: "50%" },
      { label: "Dureza Brinell", value: "160 - 190 HB" },
    ],
    chemistry: [
      { label: "%Cr", value: "16,0 - 18,0" },
      { label: "%Ni", value: "10,00 - 14,00" },
      { label: "%Mo", value: "2,0 - 3,0" },
      { label: "%C", value: "≤ 0,03" },
    ],
    uses: ["Petróleo y gas", "Farmacéutica", "Minería", "Alimentos", "Ambientes agresivos"],
  },
  {
    slug: "antidesgaste-450-500",
    name: "Láminas antidesgaste 450 / 500",
    category: "Antidesgaste",
    badge: "Alta abrasión",
    image: "/images/products/laminas-antidesgaste-wow.webp",
    intro: "Planchas antidesgaste para aplicaciones donde la abrasión, impacto y roce constante exigen mayor duración del material.",
    application: "Usadas en equipos de minería, movimiento de material, tolvas, cuchillas, revestimientos, máquinas agrícolas y piezas expuestas al desgaste.",
    properties: "Disponibles en cortes y medidas de acuerdo con la necesidad del cliente, orientadas a trabajos industriales de alto desgaste.",
    presentations: ["Láminas", "Cortes a medida", "Piezas preparadas para proyecto"],
    specs: [
      { label: "Grados", value: "450 y 500" },
      { label: "Formato", value: "Láminas y cortes" },
      { label: "Enfoque", value: "Resistencia al desgaste" },
      { label: "Servicio", value: "Corte según medida" },
    ],
    uses: ["Tolvas", "Revestimientos", "Minería", "Agroindustria", "Mantenimiento pesado"],
    featured: true,
  },
  {
    slug: "fundicion-gg25",
    name: "Hierro fundido GG-25",
    category: "Aceros grado maquinaria",
    badge: "Fundición",
    image: "/images/client-products/acero-hierro-fundido.webp",
    intro: "Hierro colado de amplio uso industrial para piezas con buena estabilidad y resistencia al desgaste.",
    application: "Usado en válvulas, bombas, tuberías y piezas automotrices.",
    properties: "Material ferroso con más de 2% de carbono y más de 1% de silicio; el carbono suele encontrarse como grafito en forma de hojuelas.",
    presentations: ["Barras redondas", "Cortes a medida", "Suministro para maquinado"],
    gallery: [
      { src: "/images/client-products/acero-hierro-fundido.webp", alt: "Hierro fundido GG-25", label: "Barra de hierro fundido" },
    ],
    specs: [
      { label: "Dureza", value: "180 - 210 HB" },
      { label: "Esfuerzo de tensión mín.", value: "172 MPa" },
      { label: "Densidad", value: "7.20 g/cm³" },
    ],
    chemistry: [
      { label: "%C", value: "3,25 - 3,5" },
      { label: "%Mn", value: "0,05 - 0,9" },
      { label: "%Si", value: "1,8 - 2,3" },
      { label: "%P", value: "≤ 0,140" },
      { label: "%S", value: "≤ 0,015" },
    ],
    uses: ["Válvulas", "Bombas", "Tuberías", "Automotriz", "Piezas mecanizadas"],
  },
  {
    slug: "aluminio-6061",
    name: "Aluminio 6061",
    category: "No ferrosos",
    badge: "Ligero",
    image: "/images/products/aluminio-wow.webp",
    intro: "Aleación dúctil y ligera con gran resistencia, excelente acabado y buena resistencia a la corrosión.",
    application: "Ideal para piezas maquinadas con buen acabado superficial y trabajos que requieren facilidad de soldadura.",
    properties: "Contiene magnesio, silicio y aluminio como elementos principales. Una de las aleaciones más comunes para uso general.",
    presentations: ["Barra redonda", "Barra cuadrada", "Angulares", "Platinas", "Láminas lisas", "Láminas corrugadas"],
    specs: [
      { label: "Límite elástico", value: "145 MPa" },
      { label: "Esfuerzo de tracción", value: "275 MPa" },
      { label: "Dureza Brinell", value: "90 HB" },
    ],
    chemistry: [
      { label: "%Si", value: "0,4 - 0,8" },
      { label: "%Mg", value: "0,8 - 1,2" },
      { label: "%Cu", value: "0,15 - 0,4" },
      { label: "%Fe", value: "≤ 0,7" },
    ],
    uses: ["Estructuras livianas", "Piezas maquinadas", "Componentes resistentes a corrosión", "Acabados industriales"],
    featured: true,
  },
  {
    slug: "bronce-fosforoso",
    name: "Bronce fosforoso C93200",
    category: "No ferrosos",
    badge: "Bujes",
    image: "/images/client-products/bronce-fosforoso-solido.webp",
    intro: "Aleación de cobre, zinc, estaño y plomo, con bajo coeficiente de fricción y alta resistencia al desgaste.",
    application: "Especial para bujes y piezas sometidas a cargas.",
    properties: "Formado por colada continua, permite piezas con buenas propiedades mecánicas y disponibilidad en barras sólidas y huecas.",
    presentations: ["Barras sólidas", "Barras huecas", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/bronce-fosforoso-solido.webp", alt: "Bronce fosforoso sólido", label: "Bronce fosforoso sólido" },
      { src: "/images/client-products/bronce-fosforoso-hueco.webp", alt: "Bronce fosforoso hueco", label: "Bronce fosforoso hueco" },
    ],
    specs: [
      { label: "Límite elástico", value: ">120 MPa" },
      { label: "Esfuerzo de tracción", value: ">270 MPa" },
      { label: "Dureza Brinell", value: ">70 HB" },
    ],
    chemistry: [
      { label: "%Cu", value: "81 - 85" },
      { label: "%Sn", value: "6 - 8" },
      { label: "%Zn", value: "3 - 5" },
      { label: "%Pb", value: "5 - 7" },
    ],
    uses: ["Bujes", "Cojinetes", "Piezas con carga", "Elementos de baja fricción"],
    featured: true,
  },
  {
    slug: "bronce-maleable",
    name: "Bronce maleable C38500",
    category: "No ferrosos",
    badge: "Latón",
    image: "/images/client-products/bronce-maleable.webp",
    intro: "También conocido como bronce latón, de alta ductilidad, resistencia a la corrosión y fácil mecanizado.",
    application: "Usado en aplicaciones decorativas, baja fricción, manijas, válvulas, fontanería, alambres, barras y perfiles.",
    properties: "Combina resistencia, ductilidad y buen comportamiento en máquinas y herramientas.",
    presentations: ["Barras", "Perfiles", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/bronce-maleable.webp", alt: "Bronce maleable", label: "Bronce maleable" },
      { src: "/images/client-products/bronce-hexagonal.webp", alt: "Bronce hexagonal", label: "Barra hexagonal de bronce" },
    ],
    specs: [
      { label: "Límite elástico", value: ">150 MPa" },
      { label: "Esfuerzo de tracción", value: ">360 MPa" },
      { label: "Dureza Brinell", value: ">90 HB" },
    ],
    chemistry: [
      { label: "%Cu", value: "57 - 59" },
      { label: "%Pb", value: "2,5 - 3,5" },
      { label: "%Fe", value: "≤0,3" },
      { label: "%Ni", value: "≤0,3" },
    ],
    uses: ["Válvulas", "Fontanería", "Perfiles", "Manijas", "Piezas mecanizadas"],
  },
  {
    slug: "bronce-aluminio",
    name: "Bronce aluminio C65500",
    category: "No ferrosos",
    badge: "Alta tracción",
    image: "/images/client-products/bronce-aluminio.webp",
    intro: "Bronce con aluminio de alta resistencia mecánica y buena resistencia a corrosión atmosférica.",
    application: "Usado en piñones, cojinetes, coronas, engranes y piezas sometidas a desgaste e impacto.",
    properties: "Elevada tenacidad, alta resistencia a tracción, abrasión, desgaste, impacto y fatiga en altas y bajas temperaturas.",
    presentations: ["Barras", "Piezas para maquinado", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/bronce-aluminio.webp", alt: "Bronce aluminio", label: "Bronce aluminio" },
    ],
    specs: [
      { label: "Límite elástico", value: ">300 MPa" },
      { label: "Esfuerzo de tracción", value: ">700 MPa" },
      { label: "Dureza Brinell", value: ">160 HB" },
    ],
    chemistry: [
      { label: "%Cu", value: "76 - 83" },
      { label: "%Al", value: "8,5 - 11" },
      { label: "%Fe", value: "3,5 - 5,5" },
      { label: "%Ni", value: "4 - 6,5" },
    ],
    uses: ["Engranes", "Coronas", "Cojinetes", "Piñones", "Piezas de impacto"],
  },
  {
    slug: "nylon-pa6",
    name: "Nylon PA-6",
    category: "Plásticos de ingeniería",
    badge: "Poliamida",
    image: "/images/client-products/nylon-barra-negra.webp",
    intro: "Termoplástico semicristalino de alta resistencia mecánica, buena resistencia al impacto y bajo peso específico.",
    application: "Usado en ruedas, engranes, poleas, piñones y piezas donde puede sustituir bronce, aluminio u otros metales no ferrosos.",
    properties: "Alta resistencia a abrasión e impacto. Puede absorber humedad, aumentando resistencia al impacto y vibraciones, con posibles cambios dimensionales.",
    presentations: ["Barras", "Láminas", "Cortes a medida"],
    gallery: [
      { src: "/images/client-products/nylon-barra-negra.webp", alt: "Barra de nylon negro", label: "Barra de nylon negro" },
      { src: "/images/client-products/nylon-lamina-negra.webp", alt: "Lámina de nylon negra", label: "Lámina de nylon negra" },
    ],
    specs: [
      { label: "Temperatura", value: "-18°C a +120°C" },
      { label: "Densidad", value: "1,15 gr/cm³" },
    ],
    uses: ["Ruedas", "Engranes", "Poleas", "Piñones", "Sustitución de metales no ferrosos"],
    featured: true,
  },
  {
    slug: "teflon-ptfe",
    name: "Teflón PTFE",
    category: "Plásticos de ingeniería",
    badge: "Baja fricción",
    image: "/images/client-products/teflon-barra-blanca.webp",
    intro: "Politetrafluoroetileno de muy baja fricción, gran resistencia química y desempeño amplio en temperatura.",
    application: "Aplicable en industria química, aeroespacial, electrónica, automotriz, médica y piezas de deslizamiento.",
    properties: "Extremadamente resistente a ácidos, bases y solventes; ideal cuando se necesitan propiedades antiadherentes o baja fricción.",
    presentations: ["Barras redondas", "Cortes a medida", "Piezas para maquinado"],
    gallery: [
      { src: "/images/client-products/teflon-barra-blanca.webp", alt: "Barra de teflón PTFE", label: "Barra de teflón PTFE" },
      { src: "/images/client-products/teflon-lamina-blanca.webp", alt: "Lámina de teflón PTFE", label: "Lámina de teflón PTFE" },
    ],
    specs: [
      { label: "Temperatura", value: "-200°C a +260°C" },
      { label: "Densidad", value: "2,2 gr/cm³" },
      { label: "Punto de fusión", value: "340°C" },
    ],
    uses: ["Sellos", "Guías", "Piezas de baja fricción", "Ambientes químicos", "Aplicaciones antiadherentes"],
  },
  {
    slug: "discos-pegatec",
    name: "Discos Pegatec",
    category: "Consumibles y corte",
    badge: "Corte y desbaste",
    image: "/images/products/discos-pegatec-wow.webp",
    intro: "Discos multipropósito de alto rendimiento para corte y desbaste de materiales industriales.",
    application: "Corte y desbaste de acero, acero inoxidable, aluminio y perfiles como láminas, tubos, ángulos y platinas.",
    properties: "Fabricados por Wingking con tecnología alemana orientada a abrasivos de alta eficiencia y calidad.",
    presentations: ["Esmerilar 4.1/2 x 1/4 x 7/8", "Corte fino 4.1/2 x 1/24 x 7/8", "Corte 7 x 1/16 x 7/8", "Corte 9 x 5/64 x 7/8", "Corte 14 x 1/8 x 1", "Corte 16 x 1/8 x 1", "Segmentado 4.1/2 x 2.1 x 7/8"],
    specs: [
      { label: "Ventajas", value: "Larga duración y alta velocidad de corte" },
      { label: "Materiales", value: "Acero, inoxidable, aluminio, cobre, aleaciones, PVA, concreto y piedra" },
      { label: "Aplicación", value: "Pared delgada, tubería sólida, barras y placas" },
    ],
    uses: ["Lijadora angular", "Tronzadora", "Desbaste", "Corte segmentado", "Procesos industriales"],
  },
  {
    slug: "acero-estructural-a36",
    name: "Acero estructural A36",
    category: "Estructurales",
    badge: "Perfiles",
    image: "/images/products/aceros-grado-maquinaria-wow.webp",
    intro: "Línea estructural para fabricación, construcción, mantenimiento y proyectos que requieren perfiles y materiales base confiables.",
    application: "Utilizado en tubos, ángulos, canales, láminas enteras, barras, vigas, platinas y cortes a medida.",
    properties: "Producto orientado a soluciones estructurales, soporte de proyectos y preparación de materiales para trabajo metalmecánico.",
    presentations: ["Láminas", "Barras", "Angulares", "Tubos", "Platinas", "Vigas", "Cortes a medida"],
    specs: [
      { label: "Material", value: "A36" },
      { label: "Formato", value: "Perfiles y láminas" },
      { label: "Servicio", value: "Corte completo o fraccionado" },
    ],
    uses: ["Estructuras", "Mantenimiento", "Construcción", "Talleres", "Proyectos industriales"],
  },
];

export const featuredMaterials = materials.filter((material) => material.featured);

export const productGroups = categories.map((category) => ({
  category,
  items: materials.filter((material) => material.category === category),
}));

export function getMaterial(slug: string) {
  return materials.find((material) => material.slug === slug);
}
